multi-threaded spa_sync
openzfs/openzfs pull request #138
Opened 2016-06-27 16:45 UTC by ahrens

spa_sync() iterates over all the dirty dnodes and processes each of them by calling dnode_sync(). If there are many dirty dnodes (e.g. because we created or removed a lot of files), the single thread of spa_sync() calling dnode_sync() can become a bottleneck. Additionally, if many dnodes are dirtied concurrently in open context (e.g. due to concurrent file creation), the os_lock will experience lock contention via dnode_setdirty().

The solution is to track dirty dnodes on a multilist_t, and for spa_sync() to use separate threads to process each of the sublists in the multilist.

On the concurrent file creation microbenchmark, the performance improvement from dnode_setdirty() is up to 7%. Additionally, the wall clock time spent in spa_sync() is reduced to 15%-40% of the single-threaded case. In terms of cost/reward, once the other bottlenecks are addressed, fixing this bug will provide a medium-large performance gain and require a medium amount of effort to implement.

Sponsored by Intel Corp.

Corresponds to ZoL bug https://github.com/zfsonlinux/zfs/issues/4807

2016-06-29 22:08 UTC, ikozhukhov commented on usr/src/uts/common/fs/zfs/dmu_objset.c
>  	while (dr = list_head(list)) {
could you update it to:
while ((dr = list_head(list)) != NULL)
for remove paretnes gcc warning

2016-06-29 22:20 UTC, ikozhukhov commented
../../common/fs/zfs/dmu_objset.c: In function 'dmu_objset_sync_dnodes':
../../common/fs/zfs/dmu_objset.c:1054:2: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
  while (dn = multilist_sublist_head(list)) {
  ^
../../common/fs/zfs/dmu_objset.c: In function 'userquota_updates_task':
../../common/fs/zfs/dmu_objset.c:1391:2: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
  while (dn = multilist_sublist_head(list)) {
  ^
cc1: all warnings being treated as errors

2016-08-15 03:19 UTC, wangdbang commented
hello, ahrens, is this effective for one zvol under multi-thread writing? thanks.

2016-08-15 16:39 UTC, ahrens commented
@wangdbang This change parallelizes syncing of different objects (dnodes).  Each zvol only has one (modified) object, so there should be no performance change when writing one zvol.

2016-08-16 00:42 UTC, wangdbang commented
@ahrens Thanks.

2017-02-16 01:24 UTC, ahrens commented
@zettabot go

2017-02-16 12:19 UTC, prakashsurya commented
@zettabot go

2017-02-16 19:04 UTC, ahrens commented on usr/src/uts/common/fs/zfs/dmu_objset.c
>  	while (dr = list_head(list)) {
Sure.

2017-03-05 04:48 UTC, ahrens commented
@zettabot go

2017-03-08 17:50 UTC, ahrens commented
@zettabot go

2017-03-08 17:58 UTC, ahrens commented
Also reviewed by @behlendorf, @pzakha, and Brad Lewis

2017-03-08 23:45 UTC, ahrens commented
@zettabot go

2017-03-09 13:14 UTC, skiselkov requested changes

2017-03-09 13:14 UTC, skiselkov commented on usr/src/uts/common/fs/zfs/sys/dmu_objset.h
> +	struct objset *os_origin_mooch_objset;
Can't seem to find the meaning of this. Maybe a leftover from earlier revisions?

2017-03-09 16:43 UTC, ahrens commented on usr/src/uts/common/fs/zfs/sys/dmu_objset.h
> +	struct objset *os_origin_mooch_objset;
@skiselkov, Thanks for taking a look.  Yeah this was due to mismergeing, I thought I fixed it yesterday but turns out it wasn't included in my push.  Will fix!

2017-03-09 16:49 UTC, skiselkov commented on usr/src/uts/common/fs/zfs/sys/dmu_objset.h
> +	struct objset *os_origin_mooch_objset;
Ok, other than this minor nit, as a whole LGTM.

2017-03-10 17:27 UTC, ahrens commented
@zettabot go

2017-03-10 17:50 UTC, skiselkov approved these changes
LGTM

2017-03-11 15:56 UTC, ahrens commented
@zettabot go

2017-03-15 13:40 UTC, ahrens commented
@zettabot go

2017-03-15 19:35 UTC, danmcd approved these changes
Approved.

2017-03-15 21:21 UTC, prashks approved these changes

2017-03-15 22:16 UTC, closed without merging

2017-03-16 01:49 UTC, lundman commented
I thought I did a commit for the missing multilist_destroy in arc.c, but since they are still missing in IllumOS maybe I was dreaming :)

```
    multilist_destroy(arc_l2c_only->arcs_list[ARC_BUFC_METADATA]);
    multilist_destroy(arc_l2c_only->arcs_list[ARC_BUFC_DATA]);
```

from https://github.com/openzfsonosx/zfs/commit/ca98a00e62bc6921df2b13810462c4770afc8c33